server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

config:
  prefix: search_
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  webinterface: /admin
  site:
    - url: https://nikoartgallery.com
      name: nikoartgallery
#    - url: http://mcrain.narod.ru
#      name: mcrain
#    - url: https://ipfran.ru/
#      name: ИПФ РАН
#    - url: https://dombulgakova.ru/
#      name: Булгаковский дом
